Move On Shake up
microsoft/pxt-microbit pull request #3634
Opened 2020-11-10 01:03 UTC by livcheerful

fixes https://github.com/microsoft/pxt-microbit/issues/3616

lemme know what you guys think! I can move it to other places if you think that'd be better This is what it looks like:
![image](https://user-images.githubusercontent.com/18712271/98614509-6e4a9400-22ad-11eb-869c-560a3100e4ef.png)
![image](https://user-images.githubusercontent.com/18712271/98614533-799dbf80-22ad-11eb-9b93-77c45c873cf8.png)

2020-11-10 07:39 UTC, pelikhan commented
Try using radio and compass in the same program.

________________________________
From: Vivian Li <notifications@github.com>
Sent: Tuesday, November 10, 2020 2:04:10 AM
To: microsoft/pxt-microbit <pxt-microbit@noreply.github.com>
Cc: Peli de Halleux <jhalleux@microsoft.com>; Review requested <review_requested@noreply.github.com>
Subject: Re: [microsoft/pxt-microbit] Move On Shake up (#3634)


@livcheerful<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flivcheerful&data=04%7C01%7Cjhalleux%40microsoft.com%7C388232006cb74b2f7f0508d8851488a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637405671131150310%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5DD6Iqqv455J%2BhsdoAqvmAv0yPXLRmSkHjzZAaTFCC0%3D&reserved=0> requested your review on: #3634<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fpull%2F3634&data=04%7C01%7Cjhalleux%40microsoft.com%7C388232006cb74b2f7f0508d8851488a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637405671131160305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nrkgWloryQ8MgP%2FfE7EzuLYRwFHKbNVhbV%2BkkIBojjk%3D&reserved=0> Move On Shake up.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fpull%2F3634%23event-3976477880&data=04%7C01%7Cjhalleux%40microsoft.com%7C388232006cb74b2f7f0508d8851488a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637405671131170304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q59vPA8%2FW5671PjlHzAjow%2B5f7zjn9vZJqCOs7TCZTg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA73QKPGSVEN4YYCES5UI6LSPCGQVANCNFSM4TQBDUNQ&data=04%7C01%7Cjhalleux%40microsoft.com%7C388232006cb74b2f7f0508d8851488a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637405671131170304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zq6X1J0s9cc6OHzbCql498GZgG36Z2CArbuyoKOmv%2FM%3D&reserved=0>.

2020-11-10 09:36 UTC, pelikhan commented
I think you want it under the 128, above the "b" label. SHAKE text would be smaller.

2020-11-10 09:37 UTC, pelikhan commented on sim/visuals/microbit.ts
>                  this.shakeText.textContent = "SHAKE"
now that we support translations in the sim, we shoud consider translating this or using an icon instead.

2020-11-10 09:38 UTC, pelikhan requested changes
Overlaps with radio antenna + RSSI text.

2020-11-10 23:48 UTC, livcheerful commented on sim/visuals/microbit.ts
>                  this.shakeText.textContent = "SHAKE"
I added pxsim.localization.lf() in two places. Is that enough for translation? (or is there a good way for me to test it?)

2020-11-11 07:27 UTC, pelikhan commented
Try using the editor in a different locale.

________________________________
From: Vivian Li <notifications@github.com>
Sent: Wednesday, November 11, 2020 12:48:54 AM
To: microsoft/pxt-microbit <pxt-microbit@noreply.github.com>
Cc: Peli de Halleux <jhalleux@microsoft.com>; Review requested <review_requested@noreply.github.com>
Subject: Re: [microsoft/pxt-microbit] Move On Shake up (#3634)


@livcheerful commented on this pull request.

________________________________

In sim/visuals/microbit.ts<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fpull%2F3634%23discussion_r520946952&data=04%7C01%7Cjhalleux%40microsoft.com%7Ce937c8e7dc544716034308d885d32f64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637406489362193400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=knLmoPgMiXRdvtEwpKRMBGeNRbCb0ShC%2B0oWIFsIh9I%3D&reserved=0>:

> @@ -475,7 +475,7 @@ path.sim-board {
                     this.board.accelerometerState.shake();
                 });
                 accessibility.setAria(this.shakeButton, "button", "Shake the board");
-                this.shakeText = svg.child(this.g, "text", { x: 400, y: 110, class: "sim-text" }) as SVGTextElement;
+                this.shakeText = svg.child(this.g, "text", { x: 400, y: 50, class: "sim-text" }) as SVGTextElement;
                 this.shakeText.textContent = "SHAKE"


I added pxsim.localization.lf() in two places. Is that enough for translation? (or is there a good way for me to test it?)

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fpull%2F3634%23discussion_r520946952&data=04%7C01%7Cjhalleux%40microsoft.com%7Ce937c8e7dc544716034308d885d32f64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637406489362193400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=knLmoPgMiXRdvtEwpKRMBGeNRbCb0ShC%2B0oWIFsIh9I%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA73QKJYS4Y6DLGZGGDLABLSPHGONANCNFSM4TQBDUNQ&data=04%7C01%7Cjhalleux%40microsoft.com%7Ce937c8e7dc544716034308d885d32f64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637406489362203392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mBq9QXmciESnozFeoGGwU%2FY7ps%2F%2Bv3WRrW4LIdIsjEE%3D&reserved=0>.

2020-11-11 07:28 UTC, pelikhan commented
Best to do this in another PR.

________________________________
From: Peli de Halleux <jhalleux@microsoft.com>
Sent: Wednesday, November 11, 2020 8:27:51 AM
To: microsoft/pxt-microbit <reply@reply.github.com>; microsoft/pxt-microbit <pxt-microbit@noreply.github.com>
Cc: Review requested <review_requested@noreply.github.com>
Subject: Re: [microsoft/pxt-microbit] Move On Shake up (#3634)

Try using the editor in a different locale.

________________________________
From: Vivian Li <notifications@github.com>
Sent: Wednesday, November 11, 2020 12:48:54 AM
To: microsoft/pxt-microbit <pxt-microbit@noreply.github.com>
Cc: Peli de Halleux <jhalleux@microsoft.com>; Review requested <review_requested@noreply.github.com>
Subject: Re: [microsoft/pxt-microbit] Move On Shake up (#3634)


@livcheerful commented on this pull request.

________________________________

In sim/visuals/microbit.ts<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fpull%2F3634%23discussion_r520946952&data=04%7C01%7Cjhalleux%40microsoft.com%7Ce937c8e7dc544716034308d885d32f64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637406489362193400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=knLmoPgMiXRdvtEwpKRMBGeNRbCb0ShC%2B0oWIFsIh9I%3D&reserved=0>:

> @@ -475,7 +475,7 @@ path.sim-board {
                     this.board.accelerometerState.shake();
                 });
                 accessibility.setAria(this.shakeButton, "button", "Shake the board");
-                this.shakeText = svg.child(this.g, "text", { x: 400, y: 110, class: "sim-text" }) as SVGTextElement;
+                this.shakeText = svg.child(this.g, "text", { x: 400, y: 50, class: "sim-text" }) as SVGTextElement;
                 this.shakeText.textContent = "SHAKE"


I added pxsim.localization.lf() in two places. Is that enough for translation? (or is there a good way for me to test it?)

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fpull%2F3634%23discussion_r520946952&data=04%7C01%7Cjhalleux%40microsoft.com%7Ce937c8e7dc544716034308d885d32f64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637406489362193400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=knLmoPgMiXRdvtEwpKRMBGeNRbCb0ShC%2B0oWIFsIh9I%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA73QKJYS4Y6DLGZGGDLABLSPHGONANCNFSM4TQBDUNQ&data=04%7C01%7Cjhalleux%40microsoft.com%7Ce937c8e7dc544716034308d885d32f64%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637406489362203392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mBq9QXmciESnozFeoGGwU%2FY7ps%2F%2Bv3WRrW4LIdIsjEE%3D&reserved=0>.

2020-11-11 17:43 UTC, jwunderl approved these changes

2020-11-11 17:43 UTC, jwunderl commented on sim/visuals/microbit.ts
> +
```suggestion
        .sim-text-small,
```

nit: seems like you can combine these two?

2020-11-11 18:03 UTC, pelikhan approved these changes
LGTM. Make sure we don't do anything with sim-text-pin in high contrast mode (where we have different sim colors).

2020-11-11 18:03 UTC, livcheerful commented on sim/visuals/microbit.ts
> +
Joey that is genius

2020-11-11 18:04 UTC, livcheerful commented
> LGTM. Make sure we don't do anything with sim-text-pin in high contrast mode (where we have different sim colors).

oh good point! I'll try it out

2020-11-11 18:32 UTC, livcheerful commented
High contrast mode doesn't change the simulator at all for me right now. I'm going to complete this PR, see what's wrong with HC, and if it affects the SHAKE text I'll open up a new PR to fix

2020-11-11 20:22 UTC, merged