better handling of nan numbers in common APIs
microsoft/pxt-microbit pull request #4623
Opened 2022-05-09 18:55 UTC by pelikhan

2022-05-09 20:18 UTC, abchatra commented on libs/core/basic.ts
> +        if (isNaN(value))
Shouldn't we just show NaN as a string?

2022-05-09 20:19 UTC, abchatra commented on libs/core/basic.ts
> +    if (isNaN(ms)) ms = 20
Good to update documentation of pause.

2022-05-09 20:21 UTC, abchatra requested changes
Looks good other than the showNumber change.

2022-05-09 20:56 UTC, pelikhan commented on libs/core/basic.ts
> +        if (isNaN(value))
NaN is meaningless for kids and in general anyone that does not have a CS background. In general, `?` felt like a more intuitive way of saying something is wrong with the input.

Also will scroll which is not great.

2022-05-09 21:22 UTC, abchatra commented on libs/core/basic.ts
> +        if (isNaN(value))
I am not sure question mark is intuitive either. Either way we have document what it means. NaN (not a number) can be used to explain? @Jaqster opinion here?

2022-05-09 21:36 UTC, pelikhan commented on libs/core/basic.ts
> +        if (isNaN(value))
I updated the docs to explain that ? is NaN... but deeper docs about NaN would be required. They've existed v1 but mostly our APIs never returned those. It's not true anymore with Jacdac when you query a sensor value where the hardware is missing.

2022-05-10 00:02 UTC, riknoll commented on libs/core/basic.ts
> +        if (isNaN(value))
I think ? is more intuitive than NaN for sure. I like this change

2022-05-20 05:01 UTC, pelikhan commented on libs/core/basic.ts
> +        if (isNaN(value))
@abchatra can we have a decision here?

2022-05-20 05:02 UTC, pelikhan commented on libs/core/basic.ts
> +        if (isNaN(value))
It's not just NaN, also "null" and "undefined" are all handled to "?".

2022-05-20 05:08 UTC, abchatra commented on libs/core/basic.ts
> +        if (isNaN(value))
I am good with your change

2022-05-20 05:18 UTC, merged